### ISSUE TITLE
Suggestions: Use Color object, add an additional 'target' parameter (or multiple) 

### ISSUE THREAD

**Issue by tiagofreirecidbr** [e-gallis/PowerApps#1]
Colors: 
There is a Color Object with several built-in colors. 
Simplifying parameters to use interchangeably the Color Object, or the RGBA object, instead of 3 inputs for each R, G and B for foreground and background, would prove useful and more familiar to PowerApps users. 

In a nutshell: replace **BarBgR, BarBgG, BarBgB** with a Background property which accepts both a **Color** or a **RGBA** input. Replace BarR, BarG, BarB with a **Foreground** property with the same behavior. 

Target Marker:
The 'target' parameter would be a marker at some point in the circleto identify a specific value in the range. 

It could be used in various ways in an application:
Used as a cap value could indicate a bad overflow condition if the value surpasses that value. 
Used as a minimum condition it would indicate that values below it are too low. 

User-accessible variables: 
input value for the target value (Number), default empty.
input value for target maker's color (RGBA or Color), default black.
input value for "foreground color if below target", (RGBA or Color) default empty.
input value for "foreground color if above target", (RGBA or Color) default empty.

**Comment by e-gallis** [comment]
Hi @tiagofreirecidbr,
I wanted to use real color objects at first, both for the background and the foregroud. Unfortunately, PowerApps does not provide a function to convert a color object value to a string.And I need the color in the string format so I can insert it within the SVG code of the progress bar image.
One thing I could do though, is to replace my R,G,B parameters with one string parameter where one could set the color by its name, its web value (#rrggbbaa) or its rgb value.
About the target marker, it's an interesting idea. I'll think about adding it to the component.

**Comment by e-gallis** [comment]
I'll leave the component as it is for now. Feel free to fork it if you wish to add the target marker feature. Closing this issue.
