### ISSUE TITLE
Could you please make the Character Width Calculator app available?

### ISSUE THREAD

**Issue by kahlkevin** [e-gallis/PowerApps#11]
In [this post](https://powerusers.microsoft.com/t5/Canvas-Apps-Components-Samples/Auto-Width-Label-Generator/td-p/534187) you (@e-gallis) described and pictured an app specially built to calculate and populate the internal font character width tables powering your [AutoWidthLabelGenerator](https://github.com/e-gallis/PowerApps/tree/master/Components/AutoWidthLabelGenerator) component:
![pictured here](https://powerusers.microsoft.com/t5/image/serverpage/image-id/135547i99E5A488AE805CDE/image-size/large?v=v2&px=999)

Is this app available?

I'm very thankful and pleased with the AutoWidthLabelGenerator, and also have some thoughts/observations/challenges:

- Support for the Courier New font is missing.
- There may be an issue with the data computed for the Patrick Hand/Lighter font weight since I'm encountering wrapping (not enough width) with some strings.
- More new fonts may come along in future.
- Contributors may wish to add support for additional characters beyond the sets you offer currently (Unicode/code points beyond ASCII).

For these reasons, **would you consider making the pictured character width calculation app available** for others to play with and use?
Either in the Apps part of this repo or perhaps via your website or upon request?

Thanks for consideration!

**Comment by e-gallis** [comment]
Done! 😉
The app is available here: https://github.com/e-gallis/PowerApps/blob/master/Components/AutoWidthLabelGenerator/FontCharWidthBuilder.zip
