### ISSUE TITLE
How to set selected default

### ISSUE THREAD

**Issue by ArtKarp** [e-gallis/PowerApps#2]
Hi,

I am testing this with three options.  When a user opens the app I want one of the options to already be selected.  I tried editing the table and setting one options "selected" to "true", but that doesn't seem to work?

How can I set an option by default to be selected?

Thanks

**Comment by ArtKarp** [comment]
Forgot to add this is about the ToggleSet.  :)

**Comment by e-gallis** [comment]
Hi @ArtKarp,
What you've done is good. The last thing to do in order to see your default values selected is to reset the component in the OnVisible event of your screen.
Tell me if this works for you (I've tested it on my side).
