### ISSUE TITLE
Office UI Fabric Icon Generator App

### ISSUE THREAD

**Issue by ArtKarp** [e-gallis/PowerApps#3]
Office UI Fabric Icon Generator is a fantastic design tool.

It would be great if theer was a solution file for CDS with an app that already has the component on a screen. This way a CDS user can skip all the setup steps and just get to work.  All they would have to do is install the solution file, run the app and start selecting/exporting icons.    If you would like to do this and need help, please let me know.

-Art

**Comment by e-gallis** [comment]
Hi @ArtKarp,
Just added a ZIP file to the component's folder. That zip file is a simple application that has the component on the first screen, thus allowing you to use it directly once the application is started.
To add the application to your tenant, just use the _Import canvas app_ from the Power Apps _Apps_ menu.
Tell me if this is good for you...
