### ISSUE TITLE
Auto Width Label Generator lblMyLabel vs Self

### ISSUE THREAD

**Issue by ArtKarp** [e-gallis/PowerApps#4]
Now that Power Apps has a "Self" reference function. Would it be better to use that instead of having to update code with each control name?    That way when you create copy/paste a label control, you eliminate having to have to edit the code.   What do you think about that?

https://powerapps.microsoft.com/en-us/blog/formulas-launch-to-self-and-self-operator/

In your nav bar where you demo changing languages, was the menu created using a gallery?   

-Thanks

**Comment by e-gallis** [comment]
Hi @ArtKarp,
Thanks for the tip. I'll definitely do that and push the new version soon.
About the changing languages control in my demo, no it's just a combo box. :)

**Comment by e-gallis** [comment]
Can't remember when I did this but it's done! 😉
