### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by ayan-b** [e-gallis/PowerApps#6]
Hi @e-gallis, thanks for the amazing work and making it open-source!

Can you please mention what is the license of this repo and if possible add a `LICENSE` file? Thank you!

**Comment by e-gallis** [comment]
All is free to be used. Icons where taken from the free ones provided by MS. Don't know if I still need to push a license file on the repo. Don't known how to do that anyway... 😬

**Comment by ayan-b** [comment]
Thanks @e-gallis!
