### ISSUE TITLE
missing menu

### ISSUE THREAD

**Issue by arkgroup** [e-gallis/PowerApps#7]
Where is left expanded/collapsed menu in Control Animator?

**Comment by e-gallis** [comment]
Sorry for the delay... The component doesn't provide the menu itself. It provides the mechanics to animate a container in Power Apps and make it look like an expandable menu. More details here: https://powerusers.microsoft.com/t5/Canvas-Apps-Components-Samples/Auto-Width-Label-Generator/td-p/534187
