### ISSUE TITLE
Label distorted on phone

### ISSUE THREAD

**Issue by novasuecia** [e-gallis/PowerApps#9]
The Circle Progress Bar looks different on PowerApps on the phone compared to on the computer. In particular, the label position is distorted and although the label setting "Visible" is set to false, it is visible on the phone.

![CircleProgressBar_Phone PNG](https://user-images.githubusercontent.com/34273699/138279952-fc4f113c-0184-487c-a193-75e2ade85656.jpg)
<img width="243" alt="CircleProgressBar_Computer" src="https://user-images.githubusercontent.com/34273699/138279959-1b6f304b-f94e-4d4a-b6c1-f6fa8b475287.PNG">

**Comment by e-gallis** [comment]
If the label shows up this way it's probably because its content is larger than the with of the label inside the component (font sizes are bigger on phones). Reduce the size of the label using the LabelSize parameter or edit the component and make the label larger... 😉
